### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by agao2** [Ballotblock/server#2]
As a developer I would like a database that can be accessed on the serverside so that I can store and verify information. 

- List of information that needs to be recoreded in a comment below

**Comment by Samulus** [comment]
Information we need to record in the database:

### Users
* Username
* Email
* Password Hash
* Salt
* Private Vote User Identity Key
* Public Vote User Identity Key
* Private Vote Value Key
* Public Vote Value Key
* List of Elections They Participated In

### Client / Server API
* Logged In Users + Their Authentication

### Elections
* Election Owner
* Election Start Date
* Election End Date
* Identity Settings
